package br.univates.sistemabancario.view.tela.autoatendimento;

import br.univates.sistemabancario.view.elements.JFrameUtilsAdapter;

/**
 * Tela responsável por permitir uma movimentação em uma conta
 * @author mateus.brambilla
 */
public class PainelMovimentacaoConta extends JFrameUtilsAdapter {

    /**
     * Creates new form PainelDepositarConta
     */
    public PainelMovimentacaoConta() {
        initComponents();
    }
    
    // Getters
    public PainelCorrentistaContaBancaria getPainelCorrentistaContaBancaria(){
        return this.painelCorrentistaContaBancaria;
    }
    
    public javax.swing.JTextPane getQuantidadeTf(){
        return this.quantidadeTf;
    }
    
    public javax.swing.JButton getButton(){
        return this.botao;
    }
    
    public javax.swing.JLabel getTitleLabel(){
        return this.labelTituloEdicaoCorrentista;
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public void adicionarAcaoBotao(java.awt.event.ActionListener listener) {
        this.botao.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCorrentistaContaBancaria = new br.univates.sistemabancario.view.tela.autoatendimento.PainelCorrentistaContaBancaria();
        labelTituloEdicaoCorrentista = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        quantidadeTf = new javax.swing.JTextPane();
        botao = new javax.swing.JButton();

        labelTituloEdicaoCorrentista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTituloEdicaoCorrentista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloEdicaoCorrentista.setText("Título");

        labelQuantidade.setText("Quantidade");

        jScrollPane1.setViewportView(quantidadeTf);

        botao.setText("Ação");
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCorrentistaContaBancaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelTituloEdicaoCorrentista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelQuantidade)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloEdicaoCorrentista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorrentistaContaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelTituloEdicaoCorrentista;
    private br.univates.sistemabancario.view.tela.autoatendimento.PainelCorrentistaContaBancaria painelCorrentistaContaBancaria;
    private javax.swing.JTextPane quantidadeTf;
    // End of variables declaration//GEN-END:variables
}
