package br.univates.sistemabancario.view.tela.autoatendimento;

import br.univates.alexandria.components.JFrameUtilsAdapter;

/**
 * Tela responsável por permitir uma movimentação em uma conta
 * @author mateus.brambilla
 */
public class PainelTransferenciaConta extends JFrameUtilsAdapter {

    /**
     * Creates new form PainelDepositarConta
     */
    public PainelTransferenciaConta() {
        initComponents();
    }
    
    // Getters
    public PainelCorrentistaContaBancaria getPainelCorrentistaContaBancariaOrigem(){
        return this.painelCorrentistaContaBancariaOrigem;
    }
    
    public PainelCorrentistaContaBancaria getPainelCorrentistaContaBancariaDestino(){
        return this.painelCorrentistaContaBancariaDestino;
    }
    
    public br.univates.alexandria.components.textfield.JCurrencyField getQuantidadeTf(){
        return this.quantidadeTf;
    }
    
    public javax.swing.JButton getButton(){
        return this.botao;
    }
    
    public javax.swing.JLabel getTitleLabel(){
        return this.labelTituloEdicaoCorrentista;
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public void adicionarAcaoBotao(java.awt.event.ActionListener listener) {
        this.botao.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCorrentistaContaBancariaOrigem = new br.univates.sistemabancario.view.tela.autoatendimento.PainelCorrentistaContaBancaria();
        labelTituloEdicaoCorrentista = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        botao = new javax.swing.JButton();
        painelCorrentistaContaBancariaDestino = new br.univates.sistemabancario.view.tela.autoatendimento.PainelCorrentistaContaBancaria();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        quantidadeTf = new br.univates.alexandria.components.textfield.JCurrencyField();

        labelTituloEdicaoCorrentista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTituloEdicaoCorrentista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloEdicaoCorrentista.setText("Transferência entre Contas");

        labelQuantidade.setText("Quantidade");

        botao.setText("Transferir");
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });

        jLabel1.setLabelFor(painelCorrentistaContaBancariaOrigem);
        jLabel1.setText("Conta de Origem");

        jLabel2.setLabelFor(painelCorrentistaContaBancariaOrigem);
        jLabel2.setText("Conta de Destino");

        quantidadeTf.setText("jCurrencyField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCorrentistaContaBancariaOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelTituloEdicaoCorrentista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelCorrentistaContaBancariaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quantidadeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelQuantidade)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloEdicaoCorrentista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorrentistaContaBancariaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorrentistaContaBancariaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao)
                    .addComponent(quantidadeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelTituloEdicaoCorrentista;
    private br.univates.sistemabancario.view.tela.autoatendimento.PainelCorrentistaContaBancaria painelCorrentistaContaBancariaDestino;
    private br.univates.sistemabancario.view.tela.autoatendimento.PainelCorrentistaContaBancaria painelCorrentistaContaBancariaOrigem;
    private br.univates.alexandria.components.textfield.JCurrencyField quantidadeTf;
    // End of variables declaration//GEN-END:variables
}
