package br.univates.sistemabancario.view.tela.autoatendimento;

import br.univates.alexandria.components.JFrameUtilsAdapter;
import br.univates.sistemabancario.view.components.ContaBancariaComboBox;
import br.univates.alexandria.components.combobox.PessoaComboBox;

/**
 * Painel com as duas combobox, de pessoa e conta bancária
 * Evita repetição nas telas de movimentação e visualização das transações
 * @author mateus.brambilla
 */
public class PainelCorrentistaContaBancaria extends JFrameUtilsAdapter {

    public PainelCorrentistaContaBancaria() {
        initComponents();
    }
    
    // Getters
    public PessoaComboBox getCbCorrentista() {
        return this.pessoaComboBox;
    }
    
    public ContaBancariaComboBox getCbContaBancaria(){
        return this.contaBancariaComboBox;
    }
    
    // Setters para ações de clique para os combobox
    public void setActionContaBancariaComboBox(java.awt.event.ActionListener listener) {
        this.contaBancariaComboBox.addActionListener(listener);
    }
    
    public void setActionPessoaComboBox(java.awt.event.ActionListener listener) {
        this.pessoaComboBox.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pessoaComboBox = new br.univates.alexandria.components.combobox.PessoaComboBox();
        contaBancariaComboBox = new br.univates.sistemabancario.view.components.ContaBancariaComboBox();
        labelContaBancaria = new javax.swing.JLabel();
        labelCorrentista = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        labelContaBancaria.setLabelFor(contaBancariaComboBox);
        labelContaBancaria.setText("ContaBancaria");

        labelCorrentista.setLabelFor(labelCorrentista);
        labelCorrentista.setText("Correntista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pessoaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCorrentista))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContaBancaria)
                    .addComponent(contaBancariaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContaBancaria)
                    .addComponent(labelCorrentista))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contaBancariaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pessoaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.univates.sistemabancario.view.components.ContaBancariaComboBox contaBancariaComboBox;
    private javax.swing.JLabel labelContaBancaria;
    private javax.swing.JLabel labelCorrentista;
    private br.univates.alexandria.components.combobox.PessoaComboBox pessoaComboBox;
    // End of variables declaration//GEN-END:variables
}
