package br.univates.sistemabancario.view.tela.correntista;

import br.univates.alexandria.components.combobox.PessoaComboBox;
import br.univates.alexandria.components.JFrameUtilsAdapter;

/**
 * Painel de edição de usuário
 * @author mateus.brambilla
 */
public class PainelEditarUsuario extends JFrameUtilsAdapter {

    public PainelEditarUsuario() {
        initComponents();
        this.textCpf.removeFocus();
    }
    
    // Getters
    public PessoaComboBox getCbCorrentista() {
        return cbCorrentista;
    }
    
    public br.univates.alexandria.components.textfield.JCpfField getCpf() {
        return textCpf;
    }
    
    public javax.swing.JTextPane getEndereco() {
        return textEndereco;
    }
    
    public br.univates.alexandria.components.textfield.JOnlyTextField getNome() {
        return textNome;
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public void adicionarAcaoBotao(java.awt.event.ActionListener listener) {
        this.botao.addActionListener(listener);
    }

    // Ação para o combobox
    public void adicionarAcaoCombobox(java.awt.event.ActionListener listener) {
        this.cbCorrentista.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        cbCorrentista = new br.univates.alexandria.components.combobox.PessoaComboBox();
        labelCorrentista = new javax.swing.JLabel();
        labelEndereco = new javax.swing.JLabel();
        botao = new javax.swing.JButton();
        labelCpf = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textEndereco = new javax.swing.JTextPane();
        try {
            textCpf = new br.univates.alexandria.components.textfield.JCpfField();
        } catch (java.text.ParseException e1) {
            e1.printStackTrace();
        }
        textNome = new br.univates.alexandria.components.textfield.JOnlyTextField();

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setLabelFor(this);
        labelTitulo.setText("Edição de Correntista");

        labelCorrentista.setLabelFor(cbCorrentista);
        labelCorrentista.setText("Correntista");

        labelEndereco.setLabelFor(textEndereco);
        labelEndereco.setText("Endereço");

        botao.setText("Editar");

        labelCpf.setText("CPF");

        labelNome.setText("Nome Completo");

        jScrollPane2.setViewportView(textEndereco);

        textCpf.setEditable(false);
        textCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textCpfFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botao))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCorrentista)
                            .addComponent(labelEndereco))
                        .addGap(0, 330, Short.MAX_VALUE))
                    .addComponent(cbCorrentista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCorrentista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCorrentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(labelCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(botao)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCpfFocusGained
        textCpf.setBorder(null);
    }//GEN-LAST:event_textCpfFocusGained

    private void textCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCpfFocusLost
        textCpf.setBorder(null);
    }//GEN-LAST:event_textCpfFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao;
    private br.univates.alexandria.components.combobox.PessoaComboBox cbCorrentista;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCorrentista;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTitulo;
    private br.univates.alexandria.components.textfield.JCpfField textCpf;
    private javax.swing.JTextPane textEndereco;
    private br.univates.alexandria.components.textfield.JOnlyTextField textNome;
    // End of variables declaration//GEN-END:variables
}
