package br.univates.sistemabancario.view.tela.navegacao;

import br.univates.alexandria.util.Messages;

/**
 * Tela que agrega todas as telas fragmentadas anteriores
 * @author mateus.brambilla
 */
public class FramePrincipal extends javax.swing.JFrame {
    
    public FramePrincipal() {        
        initComponents();  
    }
    
    public void exibirErro(String mensagem) {
        Messages.errorMessage(this, mensagem);
    }
    
    public void exibirSucesso(String mensagem) {
        Messages.sucessMessage(this, mensagem);
    }
    
    // Getters
    public javax.swing.JPanel getPainelPrincipal() {
        return this.painel;
    }

    // Getters para os Itens de Menu de Autoatendimento
    public javax.swing.JMenuItem getPaginaInicialMenuItem() {
        return paginaInicialMenuItem;
    }
    
    public javax.swing.JMenuItem getSairMenuItem() {
        return sairMenuItem;
    }
    
    public javax.swing.JMenuItem getDepositarMenuItem() {
        return depositarMenuItem;
    }
    
    public javax.swing.JMenuItem getPagarMenuItem() {
        return sacarMenuItem;
    }
    
    public javax.swing.JMenuItem getExtratoMenuItem() {
        return extratoMenuItem;
    }
    
    public javax.swing.JMenuItem getTransferenciaMenuItem() {
        return transferenciaMenuItem;
    }

    // Getters para os Itens de Menu Correntista
    public javax.swing.JMenuItem getCadastroCorrentistaMenuItem() {
        return cadastroCorrentistaMenuItem;
    }

    public javax.swing.JMenuItem getVisualizarCorrentistasMenuItem() {
        return visualizarCorrentistasMenuItem;
    }

    public javax.swing.JMenuItem getEditarCorrentistaMenuItem() {
        return editarCorrentistaMenuItem;
    }
    
    public javax.swing.JMenuItem getDeletarCorrentistaMenuItem() {
        return deletarCorrentistaMenuItem;
    }
    
    // Getters para os Itens de Menu Conta Bancaria
    public javax.swing.JMenuItem getAdicionarContaMenuItem() {
        return adicionarContaMenuItem;
    }

    public javax.swing.JMenuItem getListarContasMenuItem() {
        return listarContasMenuItem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        autoatendimentoMenu = new javax.swing.JMenu();
        depositarMenuItem = new javax.swing.JMenuItem();
        sacarMenuItem = new javax.swing.JMenuItem();
        transferenciaMenuItem = new javax.swing.JMenuItem();
        extratoMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        paginaInicialMenuItem = new javax.swing.JMenuItem();
        sairMenuItem = new javax.swing.JMenuItem();
        contabancariaMenu = new javax.swing.JMenu();
        adicionarContaMenuItem = new javax.swing.JMenuItem();
        listarContasMenuItem = new javax.swing.JMenuItem();
        correntistaMenu = new javax.swing.JMenu();
        cadastroCorrentistaMenuItem = new javax.swing.JMenuItem();
        editarCorrentistaMenuItem = new javax.swing.JMenuItem();
        deletarCorrentistaMenuItem = new javax.swing.JMenuItem();
        visualizarCorrentistasMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco Byte Desktop");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        painel.setLayout(new java.awt.CardLayout());

        autoatendimentoMenu.setText("Autoatendimento");

        depositarMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        depositarMenuItem.setText("Depositar");
        autoatendimentoMenu.add(depositarMenuItem);

        sacarMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        sacarMenuItem.setText("Sacar");
        autoatendimentoMenu.add(sacarMenuItem);

        transferenciaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        transferenciaMenuItem.setText("Transferência");
        autoatendimentoMenu.add(transferenciaMenuItem);

        extratoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        extratoMenuItem.setText("Consultar Extrato");
        autoatendimentoMenu.add(extratoMenuItem);
        autoatendimentoMenu.add(jSeparator1);

        paginaInicialMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        paginaInicialMenuItem.setText("Página Inicial");
        autoatendimentoMenu.add(paginaInicialMenuItem);

        sairMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        sairMenuItem.setText("Sair");
        autoatendimentoMenu.add(sairMenuItem);

        jMenuBar1.add(autoatendimentoMenu);

        contabancariaMenu.setText("Conta Bancária");

        adicionarContaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        adicionarContaMenuItem.setText("Adicionar Conta");
        contabancariaMenu.add(adicionarContaMenuItem);

        listarContasMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        listarContasMenuItem.setText("Listar Contas");
        contabancariaMenu.add(listarContasMenuItem);

        jMenuBar1.add(contabancariaMenu);

        correntistaMenu.setText("Correntista");

        cadastroCorrentistaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cadastroCorrentistaMenuItem.setText("Cadastro");
        correntistaMenu.add(cadastroCorrentistaMenuItem);

        editarCorrentistaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        editarCorrentistaMenuItem.setText("Editar");
        correntistaMenu.add(editarCorrentistaMenuItem);

        deletarCorrentistaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        deletarCorrentistaMenuItem.setText("Deletar");
        correntistaMenu.add(deletarCorrentistaMenuItem);

        visualizarCorrentistasMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        visualizarCorrentistasMenuItem.setText("Visualizar");
        correntistaMenu.add(visualizarCorrentistasMenuItem);

        jMenuBar1.add(correntistaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FramePrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adicionarContaMenuItem;
    private javax.swing.JMenu autoatendimentoMenu;
    private javax.swing.JMenuItem cadastroCorrentistaMenuItem;
    private javax.swing.JMenu contabancariaMenu;
    private javax.swing.JMenu correntistaMenu;
    private javax.swing.JMenuItem deletarCorrentistaMenuItem;
    private javax.swing.JMenuItem depositarMenuItem;
    private javax.swing.JMenuItem editarCorrentistaMenuItem;
    private javax.swing.JMenuItem extratoMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem listarContasMenuItem;
    private javax.swing.JMenuItem paginaInicialMenuItem;
    private javax.swing.JPanel painel;
    private javax.swing.JMenuItem sacarMenuItem;
    private javax.swing.JMenuItem sairMenuItem;
    private javax.swing.JMenuItem transferenciaMenuItem;
    private javax.swing.JMenuItem visualizarCorrentistasMenuItem;
    // End of variables declaration//GEN-END:variables
}
