package br.univates.sistemabancario.view.tela.conta;

import br.univates.alexandria.components.combobox.PessoaComboBox;
import br.univates.alexandria.components.JFrameUtilsAdapter;
import javax.swing.JRadioButton;

/**
 * Tela responsável por realizar o cadastro das contas
 * @author mateus.brambilla
 */
public class PainelCadastroConta extends JFrameUtilsAdapter {
    public PainelCadastroConta() {
        initComponents();
        getLabelLimite().setVisible(false);
        getTfLimite().setVisible(false);
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public void adicionarAcaoBotao(java.awt.event.ActionListener listener) {
        this.botao.addActionListener(listener);
    }
    
    // Modificar estado dos componentes via controller
    public void exibirCamposContaEspecial() {
        getLabelLimite().setVisible(true);
        getTfLimite().setVisible(true);
    }
    
    public void ocultarCamposContaEspecial() {
        getLabelLimite().setVisible(false);
        getTfLimite().setVisible(false);
    }
    
    // Getters
    public PessoaComboBox getCbCorrentista() {
        return this.cbCorrentista;
    }
    
    public br.univates.alexandria.components.textfield.JCurrencyField getTfLimite(){
        return this.tfLimite;
    }
    
    public javax.swing.JLabel getLabelLimite() {
        return this.labelLimite;
    }
    
    public JRadioButton getRbContaNormal() {
        return contaNormalRadioButton;
    }

    public JRadioButton getRbContaEspecial() {
        return contaEspecialRadioButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoContaButtonGroup = new javax.swing.ButtonGroup();
        labelTitulo = new javax.swing.JLabel();
        labelCorrentista = new javax.swing.JLabel();
        labelLimite = new javax.swing.JLabel();
        botao = new javax.swing.JButton();
        cbCorrentista = new br.univates.alexandria.components.combobox.PessoaComboBox();
        tfLimite = new br.univates.alexandria.components.textfield.JCurrencyField();
        contaEspecialRadioButton = new javax.swing.JRadioButton();
        contaNormalRadioButton = new javax.swing.JRadioButton();
        labelTipoConta = new javax.swing.JLabel();

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Cadastro de Conta Bancária");

        labelCorrentista.setText("Correntista");

        labelLimite.setLabelFor(tfLimite);
        labelLimite.setText("Limite");

        botao.setText("Cadastrar");

        tfLimite.setText("jCurrencyField1");

        tipoContaButtonGroup.add(contaEspecialRadioButton);
        contaEspecialRadioButton.setText("Conta Especial");

        tipoContaButtonGroup.add(contaNormalRadioButton);
        contaNormalRadioButton.setSelected(true);
        contaNormalRadioButton.setText("Conta Normal");
        contaNormalRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaNormalRadioButtonActionPerformed(evt);
            }
        });

        labelTipoConta.setText("Tipo de Conta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(cbCorrentista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botao))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCorrentista)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(contaNormalRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(contaEspecialRadioButton))
                            .addComponent(labelTipoConta))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLimite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfLimite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCorrentista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCorrentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoConta)
                    .addComponent(labelLimite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contaNormalRadioButton)
                    .addComponent(contaEspecialRadioButton)
                    .addComponent(tfLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(botao)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void contaNormalRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaNormalRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contaNormalRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao;
    private br.univates.alexandria.components.combobox.PessoaComboBox cbCorrentista;
    private javax.swing.JRadioButton contaEspecialRadioButton;
    private javax.swing.JRadioButton contaNormalRadioButton;
    private javax.swing.JLabel labelCorrentista;
    private javax.swing.JLabel labelLimite;
    private javax.swing.JLabel labelTipoConta;
    private javax.swing.JLabel labelTitulo;
    private br.univates.alexandria.components.textfield.JCurrencyField tfLimite;
    private javax.swing.ButtonGroup tipoContaButtonGroup;
    // End of variables declaration//GEN-END:variables
}
