package br.univates.sistemabancario.view;

import java.awt.Color;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

import br.univates.alexandria.models.Pessoa;
import br.univates.sistemabancario.repository.ContaBancariaDAO;
import br.univates.sistemabancario.repository.CorrentistaDAO;
import br.univates.sistemabancario.service.ContaBancaria;
import br.univates.sistemabancario.service.ContaBancariaEspecial;

/**
 *
 * @author mateu
 */
public class TelaCadastroConta extends javax.swing.JDialog {
    private final CorrentistaDAO cdao;
    private final ContaBancariaDAO cbdao;
    private final DefaultComboBoxModel<Pessoa> model;
    
    /**
     * Creates new form FrameCadastroCorrentista
     * @param parent - um JFrame
     * @param cdao - instancia de CorrentistaDAO
     * @param cbdao - instancia de ContaBancariaDAO
     */
    public TelaCadastroConta(JFrame parent, CorrentistaDAO cdao, ContaBancariaDAO cbdao) {
        super(parent, "Cadastro de Conta Bancária", true); 
        this.cdao = cdao;
        this.cbdao = cbdao;
        
        initComponents();
        this.model = new DefaultComboBoxModel<>();
        this.cbCorrentista.setModel(model);
        setLocationRelativeTo(parent);
        carregarCorrentistas();
    }
    
    private void carregarCorrentistas(){
        model.removeAllElements(); 

        model.addElement(null);

        for (Pessoa p : this.cdao.readAll()) {
            model.addElement(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        labelCorrentista = new javax.swing.JLabel();
        botaoCadastro = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        tfSaldo = new javax.swing.JTextField();
        labelSaldo = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        labelSuccessError = new javax.swing.JLabel();
        cbCorrentista = new javax.swing.JComboBox<>();
        tfNumero = new javax.swing.JTextField();
        labelLimite = new javax.swing.JLabel();
        tfLimite = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Correntistas");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 51, 51));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelCorrentista.setText("Informe o correntista:");

        botaoCadastro.setBackground(new java.awt.Color(0, 0, 51));
        botaoCadastro.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastro.setText("Cadastrar");
        botaoCadastro.setAutoscrolls(true);
        botaoCadastro.addActionListener(evt -> botaoCadastroActionPerformed(evt));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Cadastro de Conta Bancária");

        labelSaldo.setLabelFor(tfSaldo);
        labelSaldo.setText("Informe o saldo inicial (opcional):");
        labelNumero.setText("Informe o número da conta (opcional):");
        labelLimite.setText("Em caso de conta especial, informe o limite (opcional):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelLimite)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfLimite, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSaldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCorrentista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCorrentista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNumero)
                            .addComponent(tfSaldo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelSuccessError, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoCadastro)))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelTitulo)
                .addGap(12, 12, 12)
                .addComponent(labelCorrentista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCorrentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelLimite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelSuccessError, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoCadastro)
                        .addGap(29, 29, 29))))
        );

        getAccessibleContext().setAccessibleName("Contas Bancárias");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Pessoa correntista = (Pessoa) this.cbCorrentista.getSelectedItem();
            if (correntista == null) {
                throw new Exception("Por favor, selecione um correntista.");
            }

            String numeroStr = this.tfNumero.getText();
            String saldoStr = this.tfSaldo.getText();
            String limiteStr = this.tfLimite.getText();
            
            boolean hasNumero = !numeroStr.isBlank();
            
            // TypeCasting
            double saldo = saldoStr.isBlank() ? 0.0 : Double.parseDouble(saldoStr);
            double limite = limiteStr.isBlank() ? 0.0 : Double.parseDouble(limiteStr);
            
            ContaBancaria cb;
            
            // Cria a conta. Se o número não for fornecido, o construtor da ContaBancaria
            // usará o new Numero(), que prepara o objeto para o DAO definir o número.
            if (limite != 0) { // conta especial
                cb = hasNumero 
                    ? new ContaBancariaEspecial(correntista, limite, saldo, Integer.parseInt(numeroStr))
                    : new ContaBancariaEspecial(correntista, limite, saldo);
            } else { // conta normal
                cb = hasNumero
                    ? new ContaBancaria(correntista, saldo, Integer.parseInt(numeroStr))
                    : new ContaBancaria(correntista, saldo);
            }
            
            cbdao.create(cb); 
            
            this.labelSuccessError.setText("Conta bancária adicionada com sucesso!");
            this.labelSuccessError.setForeground(Color.green);
            
            this.tfNumero.setText("");
            this.tfSaldo.setText("");
            this.tfLimite.setText("");
            
            this.cbCorrentista.setSelectedIndex(0);
            
        } catch (NumberFormatException nfe) {
            this.labelSuccessError.setText("<html>Erro: Saldo, número e limite devem ser valores numéricos válidos.</html>");
            this.labelSuccessError.setForeground(Color.red);
        } catch (Exception e) {
            this.labelSuccessError.setText("<html>Erro: " + e.getMessage() + "</html>");
            this.labelSuccessError.setForeground(Color.red);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JComboBox<Pessoa> cbCorrentista;
    private javax.swing.JLabel labelCorrentista;
    private javax.swing.JLabel labelLimite;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelSuccessError;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField tfLimite;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfSaldo;
    // End of variables declaration//GEN-END:variables
}
