package br.univates.sistemabancario.view;

import br.univates.alexandria.models.Pessoa;
import br.univates.alexandria.tools.Messages;
import br.univates.sistemabancario.persist.CorrentistaDAO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author mateu
 */
public class TelaDeletarUsuario extends javax.swing.JDialog {
    private final ArrayList<Pessoa> al;
    private final CorrentistaDAO cdao;
    private final DefaultComboBoxModel<Pessoa> model;
    
    /**
     * Creates new form FrameCadastroCorrentista
     * @param parent - um JFrame
     * @param cdao - instancia de CorrentistaDAO
     * @param al - arraylist com pessoas sem contas
     */
    public TelaDeletarUsuario(JFrame parent, CorrentistaDAO cdao, ArrayList<Pessoa> al) {
        super(parent, "Cadastro de Conta Bancária", true); 
        this.cdao = cdao;
        this.al = al;
        
        initComponents();
        this.model = new DefaultComboBoxModel<>();
        this.cbCorrentista.setModel(model);
        setLocationRelativeTo(parent);
        carregarCorrentistas();
    }
    
    private void carregarCorrentistas(){
        model.removeAllElements(); 
        model.addElement(null);

        for (Pessoa p : this.al) {
            model.addElement(p);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        labelCorrentista = new javax.swing.JLabel();
        botaoCadastro = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        labelSuccessError = new javax.swing.JLabel();
        cbCorrentista = new javax.swing.JComboBox<Pessoa>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Correntistas");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 51, 51));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        labelCorrentista.setText("Informe o correntista:");

        botaoCadastro.setBackground(new java.awt.Color(0, 0, 51));
        botaoCadastro.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastro.setText("Deletar");
        botaoCadastro.setAutoscrolls(true);
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Remoção de Correntista");

        cbCorrentista.setAutoscrolls(true);
        cbCorrentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCorrentistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSuccessError, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoCadastro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbCorrentista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCorrentista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCorrentista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCorrentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(botaoCadastro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelSuccessError, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        getAccessibleContext().setAccessibleName("Contas Bancárias");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
        try{
            Pessoa correntista = (Pessoa) this.cbCorrentista.getSelectedItem();
            if (correntista == null) {
                throw new Exception("Por favor, selecione um correntista.");
            }
            
            this.cdao.delete(correntista);
            this.al.remove(correntista);
            this.cbCorrentista.removeAllItems();
            
            this.labelSuccessError.setText("Correntista deletado com sucesso!");
            this.labelSuccessError.setForeground(Color.green);
            
            carregarCorrentistas();
            
            if(this.al.isEmpty()){
                Messages.infoMessage(this, "Não há mais usuários sem conta cadastrada");
                dispose();
            }
        }catch(Exception e){
            // Html para quebra de linha
            this.labelSuccessError.setText("<html>Erro: " + e.getMessage() + "</html>");
            this.labelSuccessError.setForeground(Color.red);
        }
    }//GEN-LAST:event_botaoCadastroActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void cbCorrentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCorrentistaActionPerformed

    }//GEN-LAST:event_cbCorrentistaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JComboBox<Pessoa> cbCorrentista;
    private javax.swing.JLabel labelCorrentista;
    private javax.swing.JLabel labelSuccessError;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
